"""initial

Revision ID: 273d5000f306
Revises: 
Create Date: 2026-03-08 22:34:38.550280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273d5000f306'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('support_contact', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ssh_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_type', sa.Enum('rsa', 'ed25519', 'ecdsa', 'dsa', name='sshkeytype'), nullable=True),
    sa.Column('fingerprint', sa.String(length=512), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=512), nullable=True),
    sa.Column('ip_v4', sa.String(length=45), nullable=True),
    sa.Column('ip_v6', sa.String(length=45), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_mb', sa.Integer(), nullable=True),
    sa.Column('disk_gb', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('datacenter', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', 'decommissioned', name='serverstatus'), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('login_user', sa.String(length=255), nullable=True),
    sa.Column('login_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('running', 'stopped', 'error', 'deploying', name='appstatus'), nullable=False),
    sa.Column('config_notes', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'server_id', name='uq_app_name_server')
    )
    op.create_table('server_ssh_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('ssh_key_id', sa.Integer(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('is_host_key', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['ssh_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'ssh_key_id', name='uq_server_ssh_key')
    )
    op.create_table('ssh_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_server_id', sa.Integer(), nullable=False),
    sa.Column('target_server_id', sa.Integer(), nullable=False),
    sa.Column('ssh_key_id', sa.Integer(), nullable=True),
    sa.Column('ssh_user', sa.String(length=255), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_server_id != target_server_id', name='ck_no_self_connection'),
    sa.ForeignKeyConstraint(['source_server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['ssh_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_server_id', 'target_server_id', name='uq_ssh_connection')
    )
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('source_server_id', sa.Integer(), nullable=False),
    sa.Column('target_server_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Enum('hourly', 'daily', 'weekly', 'monthly', 'manual', name='backupfrequency'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.Enum('success', 'failed', 'running', 'never_run', name='backupstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_server_id'], ['servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backups')
    op.drop_table('ssh_connections')
    op.drop_table('server_ssh_keys')
    op.drop_table('applications')
    op.drop_table('servers')
    op.drop_table('ssh_keys')
    op.drop_table('providers')
    # ### end Alembic commands ###
